[package]
name = "mcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mbytes = {path = "../mbytes"}
mserde = {path = "../mserde"}

[lib]
name = "mcli"
path = "src/lib.rs"
